### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Janitsu** [jaymrobinson/PoETools#4]
Using the latest release you get the following error:

```
D:\Downloads\stashify>Stashify.exe /D

Unhandled Exception: System.IO.IOException: The file 'assets\black.png' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Stashify.Program.DownloadAssets(String assetDir)
   at Stashify.Program.Main(String[] args)
```

Not sure if there is any development or any will to develop the software further, but it seems like a cool application :).

**Comment by jaymrobinson** [comment]
It tries to generate a blank (black) tile automatically. Try deleting the black.png file in the assets directory.

**Comment by Janitsu** [comment]
After deleting the black.png file, the error has turned into this one.
```
D:\Downloads\stashify>Stashify.exe /D
Downloading: https://web.poecdn.com/image/Art/2DItems/Amulets/AgateAmulet.png

Unhandled Exception: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Stashify.Program.DownloadAssets(String assetDir)
   at Stashify.Program.Main(String[] args)
```

**Comment by jaymrobinson** [comment]
I'll take a closer look when I get a chance, but I think you may have to specify TLS 1.2 explicitly to get it to work now.
Try adding the following near the beginning of the main function in Program.cs.

`System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;`

**Comment by Janitsu** [comment]
Thanks, I will give it a look when I have computer access again. Quick googling suggested that it could solve this particular issue, so staying hopeful.

**Comment by p0miki** [comment]
you can look at this stackoverflow: 
https://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel

i also had the issue and used the suggested fix by adding: 
`ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = `SecurityProtocolType.Tls12;`
 and it solved the issue.

**Comment by patrick-solving-problems** [comment]
@p0miki  would you make a release with the fix?
I downloaded the exe file and I get exactly the same errors as described here

**Comment by p0miki** [comment]
@patrick-solving-problems - I be frank with you, I'm not much of a git hub user so I don't really know how to update someone else repository. If you want i uploaded my code to my google drive together with the exe at: 
https://drive.google.com/file/d/1bEWoiY8dbGbDXc9SX1CzHcw3BdRhtZ9p/view?usp=sharing

You can also just grab the assets folder from there if you don't want to mess with my code/exe - that way you can skip downloading them yourself and ignore this issue. 
Last note: if you do use my code, I changed the program a bit, to auto-convert all images that are under the folder 'toGif'. That folder is under the exe file folder. The program will still output everything to the exe directory.
